#!/usr/bin/env python3
"""Re-evaluate the tasks whose code moved, then rebuild the artifacts that report them.

`task_staleness` says WHICH generators drifted; this runs the evaluations that clear them, so
"I edited some tasks" is one command instead of a remembered sequence of scratchpad loops. Every
step is hash-aware and idempotent: cells already measured at a task's current `behavior_hash` are
skipped, so a throttled probe or a preempted job resumes instead of restarting.

    python -m reasoning_core.reports.refresh                    # plan: what drifted, what would run
    python -m reasoning_core.reports.refresh --run              # probe, then rebuild the pages
    python -m reasoning_core.reports.refresh --run --steps probe artifact
    python -m reasoning_core.reports.refresh --run --all-tasks  # ignore staleness, sweep everything

The probe generates FROM THE LIVE GENERATORS, so a task edited five minutes ago is measurable now,
with no dataset build in between. Influence needs the fleet, so that step only WRITES the submission
script -- placement stays oplog's business. Each run appends the task->hash map it acted on to
`build/refresh_log.jsonl`, which is what makes a later "was this measured?" answerable.
"""
from __future__ import annotations
import argparse, json, os, subprocess, sys, time
from pathlib import Path

from reasoning_core.reports.task_staleness import scan as staleness

ROOT = Path(__file__).resolve().parents[2]
BUILD = Path(__file__).with_name("build")
PY = sys.executable
RELEASE = os.environ.get("RC_RELEASE", "rc11.2")
# where the generator array writes its shards; only reachable from a G5K frontend
GEN_ROOT = os.environ.get(
    "RC_GEN_ROOT", "/srv/storage/magnet@storage1.lille.grid5000.fr/dsileo/generated_data")
STEPS = ["probe", "coverage", "artifact", "influence"]


def sh(cmd):
    print("  $ " + " ".join(str(c) for c in cmd), flush=True)
    return subprocess.run([str(c) for c in cmd], cwd=ROOT).returncode


def n_ok(path):
    if not Path(path).exists():
        return 0
    return sum(1 for r in json.loads(Path(path).read_text()).values() if r.get("status") == "ok")


def probe(tasks, levels, n, passes, out):
    """Repeated passes; the free tier throttles, so a pass that adds no cells is the stop condition."""
    prev = -1
    for i in range(passes):
        sh([PY, "-u", "-m", "reasoning_core.reports.zeroshot_probe", "--tasks", *tasks,
            "--levels", *levels, "--n", n, "--workers", 1, "--out", out])
        ok = n_ok(out)
        print(f"[refresh] probe pass {i + 1}: {ok} cells ok")
        if ok <= prev:
            break
        prev = ok
        time.sleep(30)


def coverage(levels_json):
    if not Path(GEN_ROOT).is_dir():
        return print(f"[refresh] SKIP coverage: {GEN_ROOT} not visible here -- run on the G5K "
                     f"frontend, or point RC_GEN_ROOT at a local copy")
    sh([PY, "-m", "reasoning_core.reports.level_coverage", "scan", "--root", GEN_ROOT,
        "--prefix", f"{RELEASE}-*", "--out", levels_json])


def artifact(levels_json, zs):
    if not Path(levels_json).exists():
        return print(f"[refresh] SKIP artifact: no {levels_json} -- run the coverage step first")
    sh([PY, "-m", "reasoning_core.reports.level_coverage", "render", "--in", levels_json,
        "--zeroshot", zs, "--out", BUILD / "levels.html"])


def influence(tasks, seed=43):
    """Emit the 360M ranking cell for the drifted tasks. Rows are CARVED from a pinned dataset
    revision, never regenerated: a regenerated row is a different row."""
    out = BUILD / f"influence_{RELEASE}.sh"
    out.write_text(f"""#!/usr/bin/env bash
# Generated by reasoning_core.reports.refresh on {time.strftime('%Y-%m-%d %H:%M')} -- do not hand-edit.
# Influence of the {len(tasks)} tasks whose generators drifted since their last measurement.
# Standard 360M ranking cell: T300, mix 0.2 BY TOKENS, max-len 1024, lr 1e-4, effective batch 8,
# plus the 2 anchors every run carries so cells stay comparable.
set -u
ST=/srv/storage/magnet@storage1.lille.grid5000.fr/dsileo
export PATH="$ST/miniconda3/bin:$PATH" PYTHONPATH="$ST/libs/reasoning_core" HOME="$ST"
export HF_HOME="$ST/.cache/huggingface" TOKENIZERS_PARALLELISM=false
cd "$ST/libs/reasoning_core" || exit 1

REV=${{REV:?set REV to the pinned {RELEASE} dataset revision}}   # from-hf defaults to a stale snapshot
TASKS="{' '.join(tasks)}"

python -m task_diagnostics.cache from-hf --repo reasoning-core/staging --revision "$REV" \\
  --tasks $TASKS --levels 0 1 2 3 4 --n 64 2>&1 | tee /tmp/cache_{RELEASE}.log
CID=$(grep -oE '[0-9a-f]{{12}}' /tmp/cache_{RELEASE}.log | tail -1)
[ -d "task_diagnostics/cache/task_rows/$CID" ] || {{ echo "!!! no cache id"; exit 1; }}

python -m task_diagnostics.collection_influence run \\
  --collections "drift=$CID,anchor=anchor2rc" --per-task \\
  --model HuggingFaceTB/SmolLM2-360M \\
  --model-revision f8027fd0eaeea54caa13c31d31b9fdc459c38b49 \\
  --max-length 1024 --learning-rate 1e-4 --batch-size 4 --gradient-accumulation-steps 2 \\
  --gradient-checkpointing --seed {seed} --steps 300 --mix 0.2 --token-ratio --share-baseline \\
  --run-tag "DRIFT_S{seed}" --experiment-id drift-{RELEASE}-360m
""")
    out.chmod(0o755)
    print(f"[refresh] wrote {out}\n  submit with: g5k.sh put <site> {out} && g5k.sh submit <site> "
          f"<cluster> {out.name} 12:0:0 1")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", action="store_true", help="execute; default is to plan only")
    ap.add_argument("--steps", nargs="+", default=STEPS, choices=STEPS)
    ap.add_argument("--all-tasks", action="store_true", help="ignore staleness; act on every task")
    ap.add_argument("--levels", nargs="+", default=["0", "2", "4", "6"])
    ap.add_argument("--n", type=int, default=3, help="probe examples per task per level")
    ap.add_argument("--passes", type=int, default=6)
    ap.add_argument("--levels-json", default=f"/tmp/levels_{RELEASE}.json")
    ap.add_argument("--zeroshot", default=str(BUILD / "zeroshot.json"))
    a = ap.parse_args()

    BUILD.mkdir(parents=True, exist_ok=True)
    rows = staleness()
    drift = [r for r in rows if a.all_tasks or r["status"] != "ok"]
    names = [r["task"] for r in drift]
    dirty = [r["task"] for r in drift if r["dirty"]]
    print(f"[refresh] {RELEASE}: {len(drift)}/{len(rows)} tasks to re-evaluate"
          + (f" ({len(dirty)} uncommitted)" if dirty else ""))
    print("  " + " ".join(names) if names else "  nothing drifted; everything is at its current hash")
    if not names:
        return
    if not a.run:
        return print(f"\n[refresh] plan only. Steps: {' '.join(a.steps)}\n"
                     f"  probe      {len(names)} tasks x {len(a.levels)} levels x {a.n} -> {a.zeroshot}\n"
                     f"  coverage   scan {GEN_ROOT}/{RELEASE}-* -> {a.levels_json}\n"
                     f"  artifact   render -> {BUILD / 'levels.html'}\n"
                     f"  influence  write {BUILD / f'influence_{RELEASE}.sh'}\n"
                     f"Re-run with --run.")

    if "probe" in a.steps:
        probe(names, a.levels, a.n, a.passes, a.zeroshot)
    if "coverage" in a.steps:
        coverage(a.levels_json)
    if "artifact" in a.steps:
        artifact(a.levels_json, a.zeroshot)
    if "influence" in a.steps:
        influence(names)
    with (BUILD / "refresh_log.jsonl").open("a") as f:
        f.write(json.dumps({"at": time.time(), "release": RELEASE, "steps": a.steps,
                            "tasks": {r["task"]: r["live"] for r in drift}}) + "\n")
    print(f"[refresh] journaled {len(drift)} task hashes -> {BUILD / 'refresh_log.jsonl'}")


if __name__ == "__main__":
    main()
