"""Emit G5K jobs measuring influence for landed tasks that have never been measured.

227 tasks have landed from task search and 174 of them have no influence cell, which is
the whole input to promotion: a task nobody has measured cannot be promoted on evidence.
This plans that measurement rather than running it, in the shape `reports.refresh` already
uses -- write the job scripts, print the two commands that stage and submit them.

Sharded on purpose. `collection_influence` writes its per-task cells only after every arm
of a run finishes, so one job holding all 174 tasks loses everything it did if it is
preempted or runs out of walltime. A shard that dies costs one shard.

Rows are built on the storage rather than carved from the published dataset, because these
tasks are not in it -- they are landed, not promoted. `g5k.sh sync` is what puts the task
code where the job can see it, and is a prerequisite.
"""
from __future__ import annotations

import argparse
import pathlib
import time

ST = "/srv/storage/magnet@storage1.lille.grid5000.fr/dsileo"
OUT_DIR = pathlib.Path("reasoning_core/reports/build")

# The 360M ranking cell every comparable run uses: T300, mix 0.2 by tokens, max-len 1024,
# lr 1e-4, effective batch 8. Kept identical to reports.refresh so the cells can be read
# beside each other instead of only against themselves.
MODEL = "HuggingFaceTB/SmolLM2-360M"
MODEL_REVISION = "f8027fd0eaeea54caa13c31d31b9fdc459c38b49"


def unmeasured(influence_json):
    """Landed generated tasks with no influence cell, in a stable order."""
    import json

    import reasoning_core as rc

    landed = sorted(set(rc.list_tasks(include_generated=True)) - set(rc.list_tasks()))
    measured = set()
    path = pathlib.Path(influence_json)
    if path.is_file():
        measured = set(json.loads(path.read_text()).get("tasks", {}))
    return [name for name in landed if name not in measured]


def script(tasks, shard, shards, seed, steps, levels, n_per_task, tag):
    return f"""#!/usr/bin/env bash
# Generated by scripts/g5k_influence_gaps.py on {time.strftime('%Y-%m-%d %H:%M')} -- do not hand-edit.
# Shard {shard} of {shards}: influence for {len(tasks)} landed tasks that have never been measured.
# Needs `g5k.sh sync` first: these tasks exist only in local commits, not in the published dataset.
set -u
ST={ST}
export PATH="$ST/miniconda3/bin:$PATH" PYTHONPATH="$ST/libs/reasoning_core" HOME="$ST"
export HF_HOME="$ST/.cache/huggingface" TOKENIZERS_PARALLELISM=false
cd "$ST/libs/reasoning_core" || exit 1

TASKS="{' '.join(tasks)}"

# Built here, not carved from the dataset: these tasks are landed, not promoted, so no
# published revision contains them. --skip-errors keeps one bad generator from costing the
# shard; a task that cannot be drawn is dropped and named in the log.
python -m task_diagnostics.cache build --tasks $TASKS \\
  --levels {' '.join(str(level) for level in levels)} --n {n_per_task} \\
  --workers 8 --skip-errors 2>&1 | tee /tmp/cache_{tag}_{shard}.log
CID=$(grep -oE '[0-9a-f]{{12}}' /tmp/cache_{tag}_{shard}.log | tail -1)
[ -d "task_diagnostics/cache/task_rows/$CID" ] || {{ echo "!!! no cache id"; exit 1; }}

python -m task_diagnostics.collection_influence run \\
  --collections "gaps=$CID,anchor=anchor2rc" --per-task \\
  --model {MODEL} --model-revision {MODEL_REVISION} \\
  --max-length 1024 --learning-rate 1e-4 --batch-size 4 --gradient-accumulation-steps 2 \\
  --gradient-checkpointing --seed {seed} --steps {steps} --mix 0.2 --token-ratio \\
  --share-baseline --run-tag "{tag}_S{seed}" --experiment-id {tag.lower()}-shard{shard}
"""


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--influence-json",
                        default="task_diagnostics/generated_influence.json")
    parser.add_argument("--shard-size", type=int, default=24,
                        help="tasks per job; a shard that dies costs one shard")
    parser.add_argument("--seed", type=int, default=43)
    parser.add_argument("--steps", type=int, default=300)
    parser.add_argument("--levels", type=int, nargs="+", default=[0, 1, 2, 3, 4])
    parser.add_argument("--n", type=int, default=64, dest="n_per_task")
    parser.add_argument("--tag", default="GAPS360")
    parser.add_argument("--site", default="grenoble")
    parser.add_argument("--cluster", default="vercors")
    parser.add_argument("--walltime", default="6:0:0")
    parser.add_argument("--tasks", nargs="*", help="override the computed gap list")
    args = parser.parse_args(argv)

    tasks = args.tasks or unmeasured(args.influence_json)
    if not tasks:
        print("nothing unmeasured; every landed task already has an influence cell")
        return
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    shards = [tasks[i:i + args.shard_size]
              for i in range(0, len(tasks), args.shard_size)]
    print(f"{len(tasks)} unmeasured tasks -> {len(shards)} shards of <={args.shard_size}\n")
    for index, shard in enumerate(shards, 1):
        name = f"influence_gaps_{index:02d}.sh"
        path = OUT_DIR / name
        path.write_text(script(shard, index, len(shards), args.seed, args.steps,
                               args.levels, args.n_per_task, args.tag))
        path.chmod(0o755)
        print(f"  {path}  ({len(shard)} tasks)")
    print("\nstage and submit (sync first, or the jobs will not find the tasks):")
    print("  g5k.sh sync " + args.site)
    for index in range(1, len(shards) + 1):
        name = f"influence_gaps_{index:02d}.sh"
        print(f"  g5k.sh put {args.site} {OUT_DIR / name} {name} && "
              f"g5k.sh submit {args.site} {args.cluster} {name} {args.walltime} 1")


if __name__ == "__main__":
    main()
